use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'YYAnimator_Example' do
  pod 'YYAnimator', :path => '../'
  pod 'Masonry',  '1.1.0'

  target 'YYAnimator_Tests' do
    inherit! :search_paths

    
  end
end
